name: Backend_LMs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.3.82.113.185 }}
          username: ${{ secrets.ubuntu }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd smartlms/lms_backend
            ./deploy.sh
